from __future__ import annotations


FINE_PIPELINE_NAME = "colmap_sparse"
LEGACY_FINE_PIPELINE_ALIASES: set[str] = set()

FINE_SCENE_PROFILE_MAX_SIDES = {
    "mixed_balanced": 1080,
    "indoor_full": 1500,
    "outdoor_fast_clean": 1080,
}
DEFAULT_FINE_SCENE_PROFILE = "mixed_balanced"
FINE_IMAGE_MAX_SIDE = 1500
FINE_ITERATIONS = 1

COLMAP_SIFT_MAX_NUM_FEATURES = 65_536
COLMAP_MAX_IMAGE_SIZE = 3_200
COLMAP_SIFT_PEAK_THRESHOLD = 0.002
COLMAP_SIFT_EDGE_THRESHOLD = 12
COLMAP_SIFT_ESTIMATE_AFFINE_SHAPE = True
COLMAP_SIFT_DOMAIN_SIZE_POOLING = True
COLMAP_GUIDED_MATCHING = True
COLMAP_SIFT_MATCH_MAX_RATIO = 0.85
COLMAP_MIN_SPARSE_POINTS = 15_000
COLMAP_TARGET_SPARSE_POINTS = 30_000
COLMAP_THREADS = 16
COLMAP_MATCHER = "exhaustive"
COLMAP_MIN_REGISTERED_RATIO = None
