from __future__ import annotations


FINE_PIPELINE_NAME = "dash_deblur_group_gs"
LEGACY_FINE_PIPELINE_ALIASES: set[str] = {"colmap_sparse"}

FINE_SCENE_PROFILE_MAX_SIDES = {
    "mixed_balanced": 3200,
    "indoor_full": 4000,
    "outdoor_fast_clean": 2400,
}
DEFAULT_FINE_SCENE_PROFILE = "mixed_balanced"
FINE_IMAGE_MAX_SIDE = 4096
FINE_DEFAULT_IMAGE_MAX_SIDE = 0
FINE_ITERATIONS = 30_000

COLMAP_SIFT_MAX_NUM_FEATURES = 65_536
COLMAP_MAX_IMAGE_SIZE = 1_080
COLMAP_SIFT_PEAK_THRESHOLD = 0.002
COLMAP_SIFT_EDGE_THRESHOLD = 12
COLMAP_SIFT_ESTIMATE_AFFINE_SHAPE = True
COLMAP_SIFT_DOMAIN_SIZE_POOLING = True
COLMAP_GUIDED_MATCHING = True
COLMAP_SIFT_MATCH_MAX_RATIO = 0.85
COLMAP_MAX_NUM_MATCHES = 32_768
COLMAP_SEQUENTIAL_OVERLAP = 60
COLMAP_MIN_SPARSE_POINTS = 0
COLMAP_TARGET_SPARSE_POINTS = 30_000
COLMAP_THREADS = 16
COLMAP_MATCHER = "exhaustive"
COLMAP_MIN_REGISTERED_RATIO = None
