from __future__ import annotations


# Balanced defaults for official FastGS-Big image fine reconstruction.
# These constants are the single source for quality/speed strategy knobs.

FINE_IMAGE_MAX_SIDE = 2400
FINE_ITERATIONS = 15_000
FASTGS_ITERATIONS = FINE_ITERATIONS

COLMAP_SIFT_MAX_NUM_FEATURES = 20_000
COLMAP_MAX_IMAGE_SIZE = FINE_IMAGE_MAX_SIDE
COLMAP_THREADS = 8
COLMAP_MATCHER = "auto"
COLMAP_MIN_REGISTERED_RATIO = None

FASTGS_SH_DEGREE = 3
FASTGS_RESOLUTION = FINE_IMAGE_MAX_SIDE
FASTGS_DATA_DEVICE = "cuda"
FASTGS_OPTIMIZER_TYPE = "default"
FASTGS_RANDOM_BACKGROUND = False

FASTGS_POSITION_LR_INIT = 0.00016
FASTGS_POSITION_LR_FINAL = 0.0000016
FASTGS_POSITION_LR_DELAY_MULT = 0.01
FASTGS_POSITION_LR_MAX_STEPS = FINE_ITERATIONS
FASTGS_FEATURE_LR = 0.0025
FASTGS_SHFEATURE_LR = 0.005
FASTGS_HIGHFEATURE_LR = 0.02
FASTGS_LOWFEATURE_LR = 0.0025
FASTGS_OPACITY_LR = 0.025
FASTGS_SCALING_LR = 0.005
FASTGS_ROTATION_LR = 0.001

FASTGS_PERCENT_DENSE = 0.001
FASTGS_DENSE = 0.005
FASTGS_MULT = 0.7
FASTGS_LAMBDA_DSSIM = 0.2
FASTGS_LOSS_THRESH = 0.1
FASTGS_GRAD_THRESH = 0.00018
FASTGS_GRAD_ABS_THRESH = 0.00035
FASTGS_DENSIFY_GRAD_THRESHOLD = 0.00018
FASTGS_DENSIFICATION_INTERVAL = 100
FASTGS_OPACITY_RESET_INTERVAL = 3_000
FASTGS_DENSIFY_FROM_ITER = 500
FASTGS_DENSIFY_UNTIL_ITER = 18_000

FASTGS_SAMPLE_CAMERAS = 12
FASTGS_VCD_PERCENTILE = 0.60
FASTGS_COMPACT_BOX_MULT = FASTGS_MULT
FASTGS_LATE_PRUNE_ENABLED = True
FASTGS_LATE_PRUNE_INTERVAL = 3_000
FASTGS_LATE_PRUNE_FROM_ITER = 15_000
FASTGS_LATE_PRUNE_UNTIL_ITER = 30_000
FASTGS_LATE_PRUNE_MIN_OPACITY = 0.10
FASTGS_LATE_PRUNE_SCORE_THRESH = 0.90
FASTGS_FINAL_PRUNE_MIN_OPACITY = 0.06
FASTGS_FINAL_PRUNE_SCORE_THRESH = 0.90

FASTGS_DEBLUR_ENABLED = "auto"
FASTGS_DEBLUR_MODE = "sharp"
FASTGS_DEBLUR_BLUR_REGISTRY = ""
FASTGS_DEBLUR_WARMUP_ITERS = 3_000
FASTGS_DEBLUR_NUM_MOMENTS = 4
FASTGS_DEBLUR_GTNET_LR = 0.001
FASTGS_DEBLUR_HIDDEN = 3
FASTGS_DEBLUR_WIDTH = 64
FASTGS_DEBLUR_LAMBDA_S = 0.01
FASTGS_DEBLUR_LAMBDA_P = 0.01
FASTGS_DEBLUR_MAX_CLAMP = 1.1
FASTGS_DEBLUR_MAX_POSITION_DELTA = 0.02
FASTGS_DEBLUR_TRANSFORM_REG_WEIGHT = 0.001
FASTGS_DEBLUR_XYZ_LR_SCALE = 0.1
FASTGS_DEBLUR_BLURRED_VIEWS_ONLY = "true"
