from __future__ import annotations


# Quality defaults for official FastGS-Big image fine reconstruction.
# These constants are the single source for quality/speed strategy knobs.

FINE_SCENE_PROFILE_MAX_SIDES = {
    "mixed_balanced": 1080,
    "indoor_full": 1500,
    "outdoor_fast_clean": 1080,
}

DEFAULT_FINE_SCENE_PROFILE = "mixed_balanced"

# 质量优先：保持 1500，不要先降分辨率
FINE_IMAGE_MAX_SIDE = 1500

# 关键：30000 轮
FINE_ITERATIONS = 30_000
FASTGS_ITERATIONS = FINE_ITERATIONS

COLMAP_SIFT_MAX_NUM_FEATURES = 20_000
COLMAP_MAX_IMAGE_SIZE = FINE_IMAGE_MAX_SIDE
COLMAP_THREADS = 8
COLMAP_MATCHER = "auto"
COLMAP_MIN_REGISTERED_RATIO = None

FASTGS_SH_DEGREE = 3
FASTGS_RESOLUTION = FINE_IMAGE_MAX_SIDE
FASTGS_DATA_DEVICE = "cuda"
FASTGS_OPTIMIZER_TYPE = "default"
FASTGS_RANDOM_BACKGROUND = False

FASTGS_POSITION_LR_INIT = 0.00016
FASTGS_POSITION_LR_FINAL = 0.0000016
FASTGS_POSITION_LR_DELAY_MULT = 0.01

# 必须跟总迭代同步
FASTGS_POSITION_LR_MAX_STEPS = FINE_ITERATIONS

FASTGS_FEATURE_LR = 0.0025
FASTGS_SHFEATURE_LR = 0.005
FASTGS_HIGHFEATURE_LR = 0.02
FASTGS_LOWFEATURE_LR = 0.0025
FASTGS_OPACITY_LR = 0.025
FASTGS_SCALING_LR = 0.005
FASTGS_ROTATION_LR = 0.001

FASTGS_PERCENT_DENSE = 0.001
FASTGS_DENSE = 0.005
FASTGS_MULT = 0.7
FASTGS_LAMBDA_DSSIM = 0.2

# 质量优先不要太激进压缩
FASTGS_LOSS_THRESH = 0.1
FASTGS_GRAD_THRESH = 0.00018
FASTGS_GRAD_ABS_THRESH = 0.00035
FASTGS_DENSIFY_GRAD_THRESHOLD = 0.00018

FASTGS_DENSIFICATION_INTERVAL = 100
FASTGS_OPACITY_RESET_INTERVAL = 3_000

# 初始 sharp warmup 加密从 500 开始
FASTGS_DENSIFY_FROM_ITER = 3000

# 如果 auto schedule 生效，这个会被调度器覆盖；
# 如果调度器没覆盖，至少保证后期还能 densify 到 25500。
FASTGS_DENSIFY_UNTIL_ITER = 25_500

FASTGS_SAMPLE_CAMERAS = 12
FASTGS_VCD_PERCENTILE = 0.60
FASTGS_COMPACT_BOX_MULT = FASTGS_MULT

# 30000 质量版：late prune 只在最后 5%~10% 轻微执行
FASTGS_LATE_PRUNE_ENABLED = True
FASTGS_LATE_PRUNE_INTERVAL = 3_000
FASTGS_LATE_PRUNE_FROM_ITER = 28_500
FASTGS_LATE_PRUNE_UNTIL_ITER = 30_000

# 不要再用 0.1，太狠，会把细节剪糊
FASTGS_LATE_PRUNE_MIN_OPACITY = 0.015
FASTGS_LATE_PRUNE_SCORE_THRESH = 0.95

# final prune 也要轻
FASTGS_FINAL_PRUNE_MIN_OPACITY = 0.005
FASTGS_FINAL_PRUNE_SCORE_THRESH = 0.95


# -------------------------
# Deblurring-3DGS settings
# -------------------------

FASTGS_DEBLUR_ENABLED = "auto"

# 如果你官方 Deblurring-3DGS 用的是 defocus，就改成 "defocus"
# 如果官方用的是 camera motion，就改成 "motion"
# 不建议默认 mixed，mixed 更慢且更容易软。
FASTGS_DEBLUR_MODE = "mixed"

FASTGS_DEBLUR_BLUR_REGISTRY = ""

# 关键：开启自动调度
FASTGS_DEBLUR_AUTO_SCHEDULE = "true"
FASTGS_DEBLUR_SCHEDULE_PROFILE = "quality"

# 这个值会被 auto schedule 覆盖到约 2400；
# 保留 2400 是为了即使调度器没覆盖，也不会 500 太早开 Deblur。
FASTGS_DEBLUR_WARMUP_ITERS = 2_400

# mixed / motion 质量优先用 5
FASTGS_DEBLUR_NUM_MOMENTS = 4

FASTGS_DEBLUR_GTNET_LR = 0.001
FASTGS_DEBLUR_HIDDEN = 3
FASTGS_DEBLUR_WIDTH = 64

FASTGS_DEBLUR_LAMBDA_S = 0.01
FASTGS_DEBLUR_LAMBDA_P = 0.01

FASTGS_DEBLUR_MAX_CLAMP = 1.1
FASTGS_DEBLUR_MAX_POSITION_DELTA = 0.02

# 质量优先可以用 1e-6；如果你发现 GTnet 学不动，可试 0.0
FASTGS_DEBLUR_TRANSFORM_REG_WEIGHT = 0.000001

FASTGS_DEBLUR_XYZ_LR_SCALE = 0.5

# 注意：这里不能有逗号
FASTGS_DEBLUR_BLURRED_VIEWS_ONLY = "false"